package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import client.utils.Service;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.control.CheckBox;

import javafx.scene.layout.VBox;
import model.SecurityModel;

public class SecurityController implements Initializable {
	@FXML
	private VBox root;
	@FXML
	private TextField txtIpActual;
	@FXML 
	private Button btnCheckIp;
	@FXML
	private ImageView imgSafe;
	@FXML
	private ImageView imvWifi;	
	@FXML
	private Label lblLocation1;
	@FXML
	private CheckBox chkProxy;
	@FXML
	private Label lblPotencialThreat;
	@FXML
	private CheckBox chkCrawler;
	@FXML
	private CheckBox chkTor;
	@FXML
	private Label lblThreatLevel;
	
	//Others
	private SecurityModel model = new SecurityModel();
	private RootController rootController; 
	private Service service = new Service();
	
	//Constructor
	
	public SecurityController() throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/SecurityView.fxml"));
		loader.setController(this);
		loader.load();
	}
	
	//Inyector	
	public void injectRootController(RootController rootController) {
		this.rootController = rootController;		
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		//Bindeos
		model.chkProxyProperty().bindBidirectional(chkCrawler.selectedProperty());
		model.chkCrawlerProperty().bindBidirectional(chkCrawler.selectedProperty());
		model.chkTorProperty().bindBidirectional(chkTor.selectedProperty());
		model.txtIpActualProperty().bindBidirectional(txtIpActual.textProperty());
		model.lblLocation1Property().bindBidirectional(lblLocation1.textProperty());
		model.lblPotencialThreatProperty().bindBidirectional(lblPotencialThreat.textProperty());
		model.lblThreatLevelProperty().bindBidirectional(lblThreatLevel.textProperty());	
		
				
	}

	// Event Listener on Button[#btnCheckIp].onAction
	@FXML
	public void onClickBtnCheckIp(ActionEvent event) {
		// TODO Autogenerated
	}
	
	

	public SecurityModel getModel() {
		return model;
	}
	
	

	public Button getBtnCheckIp() {
		return btnCheckIp;
	}

	public VBox getView() {
		return root;
	}

	
	
	
	
}
